app/courses/routes.py
# from app import db
from flask import Flask, Blueprint, render_template, request, redirect, flash, url_for
from flask_login import current_user, login_required
from app.courses.forms import CourseSearchForm
from app.courses.utils import filter_courses
from app.db.db_models import load_comments, load_course, row_to_dict, add_to_table, remove_course, CourseComments, UserSavedCourses, isCourseSaved, load_saved_courses, get_course_by_id
from app import df, G
from app import es

courses = Blueprint('courses', __name__)
search = CourseSearchForm()

"""Homepage is essentially just the course search form. If a post request is received, call the method that finds search results."""
@courses.route('/search',methods=['GET','POST'])
def home():
    search = CourseSearchForm(request.form)
    if request.method == 'POST':
        search_word = search.data['search']
        select = search.data['select']
        division = search.data['divisions']
        departments = search.data['departments']
        campuses = search.data['campuses']
        top = search.data['top']
        return redirect(url_for('courses.search_results', search_word=search_word, select=select, divisions=division, departments=departments, campuses=campuses, top=top))
        # return search_results(search)
    return render_template('index.html',form=search)


"""Handle the data from the POST request that will go to the main algorithm.
If we get an empty search, just go back to home.
Otherwise, pull out the elements of the POST request that are used by the algorithm, and get the results.
Then, render the results page with a list of pandas tables containing the results for each year.
Pass the original search to the template as well, so the user can see the context of what they asked for.
"""
@courses.route('/results/query=?q=<search_word>s=<select>d=<divisions>dp=<departments>c=<campuses>t=<top>')
@login_required
def search_results(search_word, select, divisions, departments, campuses, top):
    if search_word == '' or not search_word:
        return redirect(url_for('courses.home'))
    results = filter_courses(
        search_word,
        select,
        divisions,
        departments,
        campuses,
        top
        )
    
    return render_template('results.html',tables=[t.to_html(classes='data',index=False,na_rep='',render_links=True, escape=False) for t in results],form=search)

"""
This method shows the information about a single course.
First, some basic error handling for if a course is passed that does not exist.
Then, separate the course information into the elements which have specific display functionality and the rest, which we show in a big table.
Pass all that to render template.
"""
@courses.route('/course/<code>')
@login_required
def course(code):
    course_info = load_course(code)

    if not course_info:
        return redirect(url_for('courses.home'))

    pre = list(filter(None, course_info.prerequisites.strip(' ').split(' ')))
    coreq = list(filter(None, course_info.corequisites.strip(' ').split(' ')))
    excl = list(filter(None, course_info.exclusion.strip(' ').split(' ')))
    terms = []
    for term in course_info.terms_offered.split(' '):
        if term.isnumeric() or len(terms) == 0:
            terms.append(term)
        else:
            terms[-1] += ' ' + term
    
    commentsQuery = load_comments(code)
    comments = []
    for c in commentsQuery:
        comments.append(row_to_dict(c))

    # checking if the course is saved for the user, need to pass to frontend to render
    # appropriate button
    isSaved = isCourseSaved(current_user.username, code)

    return render_template(
        'course.html',
        code=code,
        name=course_info.name,
        description=course_info.description,
        level=course_info.course_level,
        campus=course_info.campus,
        division=course_info.division,
        department=course_info.department,
        pre=pre,
        excl=excl,
        coreq=coreq,
        terms=terms,
        comments=comments,
        isSaved = isSaved
        )

@courses.route('/course/<code>/add_comment', methods=['POST'])
@login_required
def add_comment(code):

    # Make sure that comment is not empty
    if not any(c.isalpha() for c in request.form['text']):
        return redirect(url_for('courses.course', code = code))

    # Make sure user is logged in before he tries to comment
    if current_user and current_user.username:
        comment = CourseComments(
            userId=current_user.username,
            courseId=code,
            comment=request.form['text']
        )
        add_to_table(comment)
    else:
        print('User is not currently logged in')
    
    return redirect(url_for('courses.course', code = code))

# When this function is called from the search page, the argument needs to be passed. Eg:
        #   <form action="{{ url_for('courses.save_course', course_id = course.id) }}" method="POST">
        #     <input class="btn" type="submit" value="Save">
        #   </form>
# But above, the value should say either save or unsave based on condition if course is already saved or not
# This route is called from both the search page and the course info page
# This method is used for both saving and unsaving courses
@courses.route('/course/<code>/save-course', methods = ['POST'])
@login_required
def save_course(code):
    # Validate if user has logged in
    if current_user and current_user.username:
        savedCourse = UserSavedCourses(username=current_user.username, courseId=code)

        if isCourseSaved(current_user.username, code):
            remove_course(current_user.username, code)
        else:
            add_to_table(savedCourse)
    else:
        print('User is not currently logged in')


    # Redirect back to the page originally called from
    if request.referrer:
        return redirect(request.referrer) 
    else:
        return redirect(url_for('courses.home'))


@courses.route('/course/my-courses', methods = ['GET'])
@login_required
def my_courses():

    all_user_courses = []
    if current_user and current_user.username:
        all_saved_courses = load_saved_courses(current_user.username)
        for i, course in enumerate(all_saved_courses):
            # print(f"i : {i} courseId: {course.courseId}")
            courseObj = get_course_by_id(course.courseId)
            # print(courseObj)
            if courseObj != None:
                all_user_courses.append(courseObj)
            else:
                print("Somehow the course object we got by id is null")

    return render_template('my-courses.html' , courses = all_user_courses)

app/users/routes.py
from app import bcrypt
from flask import Flask, Blueprint, render_template, request, redirect, flash, url_for
from app.db.db_models import User, add_to_table
from app.users.forms import LoginForm, CreateForm
from flask_login import login_user, current_user, logout_user

users = Blueprint('users', __name__)

@users.route('/login',methods=['GET', 'POST'])
def login():
    # Cannot log in if already logged in
    if current_user.is_authenticated:
        return redirect(url_for('searching_filtering.search_home'))
    
    form = LoginForm(meta={'csrf': False})
    if form.validate_on_submit():
        # Check user credentials
        user = User.query.filter_by(username = form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # Logs the user in and redirects to home page
            login_user(user) # can also add remember me argument here if we add remember me input in form

            # If user was trying to access a page but was redirected to login before accessing
            # we need to redirect him to that page again
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('searching_filtering.search_home'))
        else:
            # print("incorrect credentials")
            flash('Incorrect username or password, please try again', 'danger')

    return render_template('landing.html', form=form, page="login")

@users.route('/signup',methods=['GET', 'POST'])
def create():

    # Cannot create account if already logged in
    if current_user.is_authenticated:
        return redirect(url_for('searching_filtering.search_home'))

    form = CreateForm(meta={'csrf': False})
    if form.validate_on_submit():

        # Create user credentials
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, password = hashed_password, email = form.email.data)

        # Add the user to the database
        add_to_table(user)
        
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('landing.html', form=form, page="create")

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))

app/templates/_formhelpers.html
{% macro render_field(field) %}
    {{ field.label }} {{ field(**kwargs)|safe }}
{% endmacro %}

{% macro filter_render_field(field) %}
    <div class="filter">
        {{ field.label }} {{ field(**kwargs)|safe }}
    </div>
{% endmacro %}

{% macro render_textfield(field) %}
    <div class="landing-form-field">
        {{ field(**kwargs)|safe }}
    </div>
{% endmacro %} 

{% macro render_searchtextfield(field) %}
    <div class="search-box">
        {{ field(**kwargs)|safe }}
    </div>
{% endmacro %}

app/templates/base.html
<!doctype html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../static/styles/common.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% block imports %}
{% endblock %}
<head>
    <meta charset="UTF-8">
    <title>BetterPath</title>
</head>
<body>
<div id="bg-circle1"></div>
<div id="bg-circle2"></div>
<div id="bg-circle3"></div>

{% block main %}
{% endblock %}
</body>
</doctype>

app/templates/course.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block imports %}
<link rel="stylesheet" href="../static/styles/course.css">
{% endblock %}

{% block main %}
{{ macros.navbar('course') }}

<div class="main-content">
    <div class="course-info-box">
        {% if isSaved == True %}
            <div class="course-info-title-box-saved"> 
        {% else %} 
            <div class="course-info-title-box"> 
        {% endif %}
            <h3 class="text-white"> {{code}} - {{name}}</h3>
            <form class="save-course" action="{{ url_for('courses.save_course', code=code) }}" method="post">
                {% if isSaved == True %}
                    <button class="save-button btn-danger">Saved</button>
                {% else %} 
                    <button class="save-button btn-success" type="submit">Save</button>
                {% endif %}
            </form>
        </div>
        <div class="course-info-content">
            <h3>Course Information</h3>
            <p> 
                {{description}}
            </p>
            <p><b>Course Level:</b> {{level}}</p>
            <p><b>Campus:</b> {{campus}}</p>
            <p><b>Division:</b> {{division}}</p>
            <p><b>Department:</b> {{department}}</p>
            <p><b>Terms Offered:</b> {{terms|join(", ")}}</p>

            <hr>
            <h4 class="new-section-header">Requirements</h4>
            <p>
                <b>Pre-requisites:</b>
                {% if pre|length > 0 %}
                    {{ pre|join(", ") }}
                {% else %}
                    None
                {% endif %}
            </p>
            <p>
                <b>Co-requisites:</b>
                {% if coreq|length > 0 %}
                    {{ coreq|join(", ") }}
                {% else %}
                    None
                {% endif %}
            </p>
            <p>
                <b>Exclusions:</b>
                {% if excl|length > 0 %}
                    {{ excl|join(", ") }}
                {% else %}
                    None
                {% endif %}
            </p>

            {% if filters|length > 0 %}
            <hr>
            <h4 class="new-section-header">Related Filters</h4>
            <div class="info-list">
                {% for filter in filters %}
                    <p class="list-item">{{prereq[0]}} </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>

    <div class="comments-box">
        <div class="course-comments-title-box">
            <h3>Comments</h3>
        </div>
        <ul class="comments-list" id="comments-list">
            {% for comment in comments %}
            <li class="comment">
                <div><b>{{comment.userId}}</b></div>
                {{comment.comment}}
            </li>
            {% else %}
            <div class="empty-list"><em>There are no comments yet.</em></div>
            {% endfor %}
        </ul>
        <div class="comment-entry">
            <hr>
            <form
                action="{{ url_for('courses.add_comment', code=code) }}"
                method="post"
                class="add-comment"
            >
                <textarea name="text" placeholder="Your comment..."></textarea>
                <input class="comment-button" type="submit" value="Post" />
            </form>
        </div>
    </div>
</div>

<script>
    window.onload = function() {
        var commentsList = document.querySelector('#comments-list');
        commentsList.scrollTop = commentsList.scrollHeight;
    }
</script>
{% endblock %}

app/templates/index.html
<!doctype html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<head>
  <meta charset="UTF-8">
    <title>Education Pathways</title>
</head>
<a href="https://carte.utoronto.ca/" target="_blank"><img src="/static/CARTE_logo.jpg" class="img-fluid" style="max-width: 25%"></a>
<h1 style="text-align: center">Education Pathways</h1>
    
<p>Welcome to CARTE's in-development tool for course selection at UofT. Education Pathways allows for more intelligent course searching, by matching not just the terms you search, but ones relevant to them. The more terms you search for, the more relevant your results will be! Even try searching across disciplines for the courses that best cover each.</p>
<p>Whatever year you are looking for, Education Pathways will also suggest courses in earlier years that will best help you to prepare. To get the most out of this, try searching for courses in a later year and see what is suggested for your current one.</p>
<p>We are looking for feedback to improve Education Pathways and make it more useful for students. If you have ideas or suggestions, please <a href="mailto:alex.olson@utoronto.ca">email us!</a></p>

{% from "_formhelpers.html" import render_field %}
<form method="post">
  <dl>
    {{ render_field(form.select) }}
    <p>
        Restrict by one of: {{ render_field(form.divisions) }} or {{ render_field(form.departments) }} or {{ render_field(form.campuses) }}
    </p> 
    <p>
    {{ render_field(form.search) }}
  </p></dl>
  <p>{{render_field(form.top)}} <input type="submit" value="Search">
</p></form>
</doctype>

app/templates/landing.html
{% extends "base.html" %}

{% block imports %}
<link rel="stylesheet" href="../static/styles/landing.css">
<link rel="stylesheet" href="../static/styles/search.css">
{% endblock %}

{% block main %}
<div class="landing-form">
    {% if form.errors %}
        <h3>Sorry...</h3>
    {% elif page == "login" %}
        <h3>Welcome Back</h3>
        <h3 class="logo">BetterPath</h3><br>
    {% elif page == "create" %}
        <h3>Sign Up</h3>
        <h1 class="logo">BetterPath</h1><br>
    {% endif %}

    <!-- Print flash error messages -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% if "created" in messages[-1] %}
            <h6 class = "text-success">{{ messages[-1] }}</h6>
        {% else %} 
            <h6 class = "text-danger">{{ messages[-1] }}</h6>
        {% endif %}
    {% endif %}
    {% endwith %}

    {% from "_formhelpers.html" import render_textfield %}
    <form method="post">
        <!-- Generating the csrf token -->
        {{ form.csrf_token }} 
        <!-- Rendering the form's hidden fields -->
        {{ form.hidden_tag() }}
        <div class="landing-form-input-box">
            {% if form.email %}
                {{ render_textfield(form.email) }}
            {% endif %}
            {{ render_textfield(form.username) }}
            {{ render_textfield(form.password) }}
            {% if form.confirm_password %}
                {{ render_textfield(form.confirm_password) }}
            {% endif %}
        </div>
        {% for field, error in form.errors.items() %}
            <div class="landing-form-error">
                {{ ', '.join(error) }}
            </div>
        {% endfor %}
        {{ form.submit(class="landing-button") }}
    </form>
    {% if page == "login" %}
        <a class="landing-redirect" href= "{{ url_for('users.create') }}" >Create an account</a>
    {% elif page == "create" %}
        <a class="landing-redirect" href= "{{ url_for('users.login') }}" >Already have an account?</a>
    {% endif %}
</div>
{% endblock %}

app/templates/macros.html
{% macro navbar(page) -%}
<!--  bg-primary  -->
 <nav class="navbar navbar-expand-lg navbar-dark " style="background-color:#355386">
     <div class="container-fluid">
         <a class="navbar-brand" style="color: white; font-family: 'Pacifico', cursive;" href="/">BetterPath</a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" style="color: white;" href="/">Search</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" style="color: white;" href="{{ url_for('courses.my_courses') }}">Saved Courses</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" style="color: white;" href="{{ url_for('users.logout') }}">Log Out</a>
                 </li>
             </ul>
         </div>
     </div>
 </nav>
 {%- endmacro %}

app/templates/my-courses.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block imports %}
<link rel="stylesheet" href="../static/styles/my-courses.css">
{% endblock %}

{% block main %}
{{ macros.navbar('search') }}
<div class="course-info-title-box">
    <h1 class="course-info-title">Saved Courses</h1>
</div>
<div class="course-info-box">
    {% for course in courses %}
        <div class=flex>
            <div class="saved-courses-list">
                <p>{{course.courseId}} - {{course.name}}</p>
            </div>
            <button class="more-info-button" type="button">
                <a class="more-info-button-text" href= "{{ url_for('courses.course', code = course.courseId) }}">
                    More Info
                </a>
            </button>
            <form class="remove-button" action="{{ url_for('courses.save_course', code = course.courseId) }}" method="POST">
                <input class="remove-button-text" type="submit" value="Remove">
            </form>
        </div>
        <hr size="2" class="line"><hr/>
    {% endfor %}          
</div>
{% endblock %}

app/templates/results.html
<!DOCTYPE html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Education Pathways</title>
</head>
<a href="https://carte.utoronto.ca/" target="_blank"><img src="/static/CARTE_logo.jpg" class="img-fluid" style="max-width: 25%"></a>
<h1 style="text-align: center">Education Pathways</h1>

<body>
    {% from "_formhelpers.html" import render_field %}
    <form method="post">
      <dl>
        {{ render_field(form.select) }}
        <p>
          Restrict by one of: {{ render_field(form.divisions) }} or {{ render_field(form.departments) }} or {{ render_field(form.campuses) }}
        </p> 
        <p>
        {{ render_field(form.search) }}
      </p></dl>
      <p>{{render_field(form.top)}} <input type="submit" value="Search">
      </p></form>
    
{% for table in tables %}
            {{ table|safe }}
{% endfor %}
</body>
</html>

app/templates/search.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block imports %}

<!-- need to use url_for() to find the the neccessary css files after search results redirect! -->
<link rel="stylesheet" href="{{ url_for('static', filename='styles/common.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='styles/landing.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='styles/search.css') }}">

{% endblock %}


{% block main %}

<!-- importing the navbar, general to all the pages -->
{{ macros.navbar('search') }}

<!-- Logo and Main Title -->
<div class="middle-search">
    <h1 class="logo">BetterPath</h1>
    <h3>Search For Courses</h3>
</div>
<div class="search-form">
    {% from "_formhelpers.html" import render_searchtextfield, filter_render_field%}
    <form method="post">
        <!-- Search Bar -->
        <div class="centering2">
            {{ render_searchtextfield(search_form.keywords) }}
        </div>
        <!-- Search Button -->
        <div class="centering">
            {{ search_form.search(class="search-landing-button") }}
        </div>
        <!-- Centering all the Filers into Rectangle Object, below Search Button -->
        <div class="rectangle">
            <h5 class="filter-title">Filters</h5>
            <div class="filter-row">
                <!-- Dropdown menus for the filters -->
                <div class="row-item">
                    {{ filter_render_field(filter_form.select) }}
                </div>
                <div class="row-item">
                    {{ filter_render_field(filter_form.divisions) }}
                </div>
                <div class="row-item">
                    {{ filter_render_field(filter_form.campuses) }}
                </div>
            </div>
        </div>
    </form> 
</div>

{% endblock %}

app/templates/searchresults.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block imports %}

<!-- need to use url_for() to find the the neccessary css files after search results redirect! -->
<link rel="stylesheet" href="{{ url_for('static', filename='styles/common.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='styles/landing.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='styles/search.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='styles/results.css') }}">

{% endblock %}

{% block main %}
<!-- importing the navbar, general to all the pages -->
{{ macros.navbar('results') }}

<br><br>

<h1>Search Results</h1>

<br> <br> <br> <br>

{% if data != [] %}
    <!-- Alignment and creating a scrollbar for the entire table -->
    <div class="middle scrollbar">
        <!-- Using bootstrap classes + customized class to design results table -->
        <table align="center" class=" table mb-0 text-center table-sm scroll-y ">
            <tbody>
            <tr class="heading">
                <td> Code </td>
                <td> Name </td>
                <td> Division </td>
                <td> Course Level </td>
                <td> Campus </td>
                <td></td>
                <td></td>
            </tr>
            <!-- Looping through the customized list of dicts to display search results in the table -->
            {% for course in data %}
                <tr style="text-align: center;">
                    {% set ns = namespace(course_url="/course/") %}
                    <td> {{ course["Code"] }} </td>
                    <td> {{ course["Name"] }} </td>
                    <td> {{ course["Division"] }}</td>
                    <td> {{ course["Course Level"] }}</td>
                    <td> {{ course["Campus"] }}</td>
                    {% set ns.course_url = ns.course_url + course["Code"] %}
                    <td><a class="btn btn-primary table-button" href= "{{ ns.course_url }}">More Info</a></td>
                    <form class="save-course" action="{{ url_for('courses.save_course', code=course["Code"]) }}" method="post">
                        {% if course["isSaved"] == True %}
                            <td><button class="btn btn-primary btn-danger table-button-saved">Saved</button></td>
                        {% else %}
                            <td><button class="btn btn-primary table-button">Save Course</button></td>
                        {% endif %}
                    </form>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- call back to search page at the bottom -->
    <div class="below-table">
        <a href="/" style="font-size: 22px; font-family: 'Open Sans';"> Return to Search </a>
    </div>
{% else %}
    <!-- fallback message for null search results from the query -->
    <div class="middle-search">
        <h3 style="margin: 0 auto;">Sorry, There are No Courses Matching Your Search! </h1>
        <a href="/" style="font-size: 22px; margin: 0 auto;"> Click Here to Return Back to Search! </a>
    </div>
{% endif %}


{% endblock %}